# name: "Chromatic"
# on: push
# jobs:
#   chromatic-deployment:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1
#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: "14"
#           cache: "npm"
#       - name: Dependencies
#         run: npm i
#       - name: Publish to Chromatic
#         uses: chromaui/action@v1
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
